openvpn:
    hosts:
        src1:
            ansible_host: 192.168.56.201
            ansible_user: vagrant
            ansible_pass: vagrant
            ansible_python_interpreter: /usr/bin/python3

server:
    children:
        openvpn
