- name: Check is docker installed
  shell: command -v docker >/dev/null 2>&1
  register: is_docker_installed
  ignore_errors: yes

- name: Install docker
  ansible.builtin.shell: cd ~ && curl -fsSL https://get.docker.com -o get-docker.sh && sudo sh get-docker.sh
  when: is_docker_installed.rc == 127  # returns pc 0 if installed or 127 if not

- name: Install dependencies
  become: yes
  apt:
    name:
      - git
      - python3-pip
    state: present
    update_cache: yes

- name: Clone github repo
  ansible.builtin.git:
    repo: 'https://github.com/mdn/django-locallibrary-tutorial.git'
    dest: /home/vagrant/app

- name: Copy dockerfile in git repo
  shell: "cp /home/vagrant/vagrant_data/Dockerfile /home/vagrant/app"

- name: Stop django instance
  docker_container:
    name: my-django
    state: stopped

- name: Build an image and push it to a private repo
  community.docker.docker_image:
    build:
      path: ./home/vagrant/app
    name: team/1lab
    tag: 1.0
    source: build

- name: Run django instance
  docker_container:
    name: my-django
    image: team/1lab:1.0
    state: started
    recreate: yes
    published_ports:
      - 80:80
