- name: Copy dockerfile in git repo
  shell: "cp /home/vagrant/vagrant_data/Dockerfile /home/vagrant/app"

- name: Build an image
  community.docker.docker_image:
    build:
      path: /home/vagrant/app
    name: team/1lab
    tag: 1.0
    source: build

- name: Run django instance
  docker_container:
    name: my-django
    image: team/1lab:1.0
    state: started
    recreate: yes
    published_ports:
      - 80:80
