---
- hosts: app
  tasks:
    - name: Check is docker installed
      shell: command -v docker >/dev/null 2>&1
      register: is_docker_installed
      ignore_errors: yes

    - name: Install docker
      ansible.builtin.shell: cd ~ && curl -fsSL https://get.docker.com -o get-docker.sh && sudo sh get-docker.sh
      when: is_docker_installed.rc == 127  # returns pc 0 if installed or 127 if not

    - name: Install git
      become: yes
      apt:
        name: git
        state: present
        update_cache: yes

    - name: Clone github repo
      shell: "rm -rf ~/app &&
              mkdir ~/app &&
              git clone https://github.com/mdn/django-locallibrary-tutorial.git temp &&
              mv -f temp/* ~/app &&
              rm -rf temp"

    - name: Install dependencies
      become: yes
      apt:
        name:
          - python3-pip

    - name: Copy dockerfile in git repo
      shell: "cp ~/vagrant_data/Dockerfile ~/app"

    - name: Stop django instance
      become: yes
      shell: "docker kill $(docker ps -q) && docker rm $(docker ps -a -q)"
      ignore_errors: yes

    - name: Run django instance
      become: yes
      shell: "docker build -t team/1lab:1.0 /home/vagrant/app &&
              docker run -d -p 80:80 --name my-django team/1lab:1.0"